[server]
18.130.208.33 k3s_private_ip=10.0.1.192

[agents]
13.134.28.72 k3s_private_ip=10.0.1.61
18.135.154.105 k3s_private_ip=10.0.1.201

[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
k3s_server_private_ip=10.0.1.192
